version: "3"

services:

  ps_db:
    image: mysql:5.7
    container_name: ps_db
    env_file: .env

  ps_web:
    build:
      context: ./
      dockerfile: .docker/Dockerfile
      args:
        - PS_VERSION=$PS_VERSION
    user: root
    container_name: ps_web
    env_file: .env
    volumes:
      - /var/www/html:/var/www/html
    ports:
      - 80:80

networks:
  ps-net: