name: Nightly upgrades

on: [push, pull_request]

jobs:
  upgrade:
    runs-on: ubuntu-latest
    env:
      nightly-storage: https://storage.googleapis.com/prestashop-core-nightly
      api-addons: https://api-addons.prestashop.com
      id-module: 5496

    strategy:
      matrix:
        ps_version_from:
          - to_download: 1.7.4.4
            for_test: 1.7.4
          #- to_download: 1.7.5.2
           # for_test: 1.7.5
          #- to_download: 1.7.6.9
           # for_test: 1.7.6
          #- to_download: 1.7.7.1
           # for_test: 1.7.7

        ps_version_to:
          - for_test: 1.7.7
            filename: 1.7.7.x-prestashop-1.7.7.2.zip
          - for_test: 1.7.8
            filename: develop-prestashop-1.7.8.0.zip

      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Get today date
        run: echo "TODAY_DATE=`date -u +"%Y-%m-%d"`" >> $GITHUB_ENV

      - uses: suisei-cn/actions-download-file@v1
        name: Download nightly file
        with:
          url: ${{ env.nightly-storage }}/${{ env.TODAY_DATE }}-${{ matrix.ps_version_to.filename }}
          target: "nightly-build/"

      - name: Build PrestaShop ${{ matrix.ps_version_from.to_download }} on docker
        env:
          PS_VERSION: ${{ matrix.ps_version_from.to_download }}
        shell: bash
        run : docker-compose -f docker-compose.yml up -d

      - name: Wait for prestashop to be ready
        uses: juliangruber/sleep-action@v1
        with:
          time: 60s

      - name: Install autoupgrade module
        shell: bash
        run: |
          docker exec -u www-data ps_web /var/www/html/bin/console --env=prod prestashop:module install autoupgrade
          docker exec -u www-data ps_web mkdir -p /var/www/html/modules/autoupgrade/download
          docker exec -u www-data ps_web cp \
            /nightly-build/${{ env.TODAY_DATE }}-${{ matrix.ps_version_to.filename }} \
            /var/www/html/modules/autoupgrade/download/${{ env.TODAY_DATE }}-${{ matrix.ps_version_to.filename }}

      # Run tests
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 10
      - name: Install dependencies
        run: npm install
      - name: Run tests
        env:
          URL_FO: "http://localhost/"
          PS_VERSION: ${{ matrix.ps_version_from.for_test }}
          PS_VERSION_UPGRADE_TO: ${{ matrix.ps_version_to.for_test }}
          DOWNLOAD_PATH: "./nightly-build"
          PROJECT_PATH: "./public"
          ZIP_NAME: ${{ env.TODAY_DATE }}-${{ matrix.ps_version_to.filename }}
        run: npm run test
      - uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: my-artifact
          path: ./screen.png