name: Nightly upgrades

on: [push, pull_request]

jobs:
  upgrade:
    runs-on: ubuntu-latest
    env:
      nightly-storage: https://storage.googleapis.com/prestashop-core-nightly

    strategy:
      matrix:
        ps_version_from:
          - to_download: 1.7.4.4
            for_test: 1.7.4
          - to_download: 1.7.5.2
            for_test: 1.7.5
          - to_download: 1.7.6.9
            for_test: 1.7.6
          - to_download: 1.7.7.1
            for_test: 1.7.7

        ps_version_to:
          - for_test: 1.7.7
            filename: 1.7.7.x-prestashop-1.7.7.2.zip
          - for_test: 1.7.8
            filename: develop-prestashop-1.7.8.0.zip

      fail-fast: false

    steps:
      - name: Get today date
        run: echo "TODAY_DATE=`date -u +"%Y-%m-%d"`" >> $GITHUB_ENV
      - uses: suisei-cn/actions-download-file@v1
        name: Download nightly file
        with:
          url: ${{ env.nightly-storage }}/${{ env.TODAY_DATE }}-${{ matrix.ps_version_to.filename }}
          target: nightly-build/
      - name: Build PrestaShop ${{ matrix.ps_version_from.to_download }} on docker
        env:
          VERSION: ${{ matrix.ps_version_from.to_download }}
        shell: bash
        run : |
          docker-compose up -d
          bash -c 'while [[ "$(curl -L -s -o /dev/null -w %{http_code} http://localhost:8001/index.php)" != "200" ]]; do sleep 5; done'

      # Run tests
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 10
      - name: Install dependencies
        run: npm install
      - name: Run tests
        env:
          URL_FO: "http://localhost:8081/"
          PS_VERSION: ${{ matrix.ps_version_from.for_test }}
          PS_VERSION_UPGRADE_TO: ${{ matrix.ps_version_to.for_test }}
          DOWNLOAD_PATH: nightly-build
          ZIP_NAME: ${{ env.TODAY_DATE }}-${{ matrix.ps_version_to.filename }}
        run: npm run test